baseurl = "https://hightower.space/"
title = "Floyd"
theme = "hugo-theme-texify"
languageCode = "en"
paginate = 7

[[menu.main]]
name = "Reading Lists"
url = "/categories/reading-list"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

# [[menu.main]]
# name = "Projects"
# url = "/categories/projects"
# weight = 1

[[menu.main]]
name = "Skills"
url = "/skills"
weight = 4

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 5

[[menu.main]]
name = "About"
url = "/about"
weight = 10

[markup]
  [markup.goldmark.renderer]
    unsafe = true # Allow HTML in md files
  [markup.highlight]
    style = "paraiso-dark"

[params]
  rss = true
  mathjax = true
  favicon = "img/favicon.ico"

  footnote = """
<a class=link href=https://github.com/fhightower>GitHub</a> |
<a class=link href=https://500px.com/p/fhightower?view=photos>500px</a> |
<a class=link href=mailto:floyd.hightower27@gmail.com>Email</a> |
<a class=link href=/index.xml>RSS</a>
"""

  description = "A digital space for sharing my thoughts."

  [params.outdated]
  enable = true # whether to display warnings for outdated posts
  limit = 1000   # days between last modified time and outdated time
  warning = "⚠️ It has been <i>%d</i> days since the last update, the content of the article may be outdated."

