version: '3.4'

services:
  _base:
    &base
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/code
    ports:
      - "8888:8888"

  # a fully loaded development environment to test new code
  dev:
    <<: *base
    command: bash

  jupyter:
    <<: *base
    entrypoint: "jupyter-lab"
    command: ["--ip", "0.0.0.0", "--allow-root"]

  voila:
    <<: *base
    entrypoint: "voila"
    command: ["./notebooks", "--port=8888", "--no-browser", "--show_tracebacks=True", "--strip_sources=False"]
